#!/usr/bin/env python3
import sys
import re
import os

if not sys.argv[1:]:
    print('You must supply a search expression!')
    exit()

homedir = os.path.expanduser('~')

try:
    regex = re.compile(sys.argv[1])
except re.error:
    print('Invalid search expression!')
    exit()

ANSI_GREEN = '\033[92m'
ANSI_HALT = '\033[0m'

history = []
matched_history = []

with open(homedir+"/.bash_history") as histfile:
    for line in histfile:
        history.append(line)

for command in history:
    if regex.match(command):
        matched_history.append(command)

if len(matched_history) == 0:
    print('No commands match your query.')
    exit()

print(ANSI_GREEN + 'Commands matching ' + sys.argv[1] + ':' + ANSI_HALT + '\n')

for i in range(len(matched_history)):
    print(str(i) + ') ' + matched_history[i].replace('\n',''))

selection = input(ANSI_GREEN + 'Command to run or Q to cancel: ' + ANSI_HALT)

if selection.lower() == "q":
    exit()

try:
    selection_index = int(selection)
except ValueError:
    print('Incorrectly formatted input caught!')
    exit()

os.system(matched_history[int(selection)])
