#!/usr/bin/env python3
import sys
import re
import os

if not sys.argv[1:]:
    print('You must supply a search expression!')
    exit()

homedir = os.path.expanduser('~')

try:
    regex = re.compile(sys.argv[1])
except re.error:
    print('Invalid search expression!')
    exit()

ANSI_GREEN = '\033[92m'
ANSI_HALT = '\033[0m'

history = []
matched_history = []

with open(homedir+"/.bash_history") as histfile:
    for line in histfile:
        history.append(line)

for command in history:
    if regex.match(command):
        matched_history.append(command)

if len(matched_history) == 0:
    print('No commands match your query.')
    exit()

#Remove duplicate entries
uniq_matched_history = []
[uniq_matched_history.append(x) for x in matched_history if x not in uniq_matched_history]

print(ANSI_GREEN + 'Commands matching ' + sys.argv[1] + ':' + ANSI_HALT + '\n')

for i in range(len(uniq_matched_history)):
    print(str(i) + ') ' + uniq_matched_history[i].replace('\n',''))

selection = input(ANSI_GREEN + 'Command(s) to run or Q to cancel: ' + ANSI_HALT)

if selection.lower() == "q":
    exit()

selections = selection.split(',')

for index in selections:
    try:
        selection_index = int(index)
    except ValueError:
        exit()

    os.system(uniq_matched_history[selection_index])
